
run:
  timeout: 5m
  go: '1.21'

linters:
  disable-all: true
  enable:
    - govet
    - ineffassign
    - typecheck
    - errcheck
    - staticcheck

linters-settings:
  govet:
    check-shadowing: false
  errcheck:
    check-type-assertions: false

issues:
  exclude-use-default: true
  max-issues-per-linter: 50
  max-same-issues: 10
